### ISSUE TITLE
Clicked TreeViewItem highlighting

### ISSUE THREAD

**Issue by mangelovic** [cmyksvoll/MultiSelectTreeView#1]
I am sorry if this should not be a case of creating issue.
But I wanted to ask, what makes in this solution prevention of "default" highlighting when I click on some item in TreeView? I am just expanding existing solution with this one, but cannot get rid of clicked item highlighting. (If I unselect with control + click, item is unselected, but it keeps highlighted as it was clicked)

Thanks for any help

**Comment by cmyksvoll** [comment]
This is done by overriding the default style for TreeViewItem.
Lines 11-133 in MainWindow.xaml.cs contain a copy of the default style.
Lines 103-114 are commented out to disable the default handling for setting selection highlighting.
